from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version


def _resolve_version() -> str:
    # Prefer installed package metadata (works for normal installs / wheels).
    try:
        return _pkg_version("awsume")
    except PackageNotFoundError:
        pass
    # Fall back to the file generated by setuptools-scm at build time, which is
    # present in source checkouts that have been built.
    try:
        from awsume._version import version as _scm_version  # noqa: PLC0415

        return _scm_version
    except ImportError:
        # Last resort: an unversioned/dev checkout with no build artifacts.
        return "0.0.0"


version = _resolve_version()

name = "awsume"
author = "Trek10, Inc"
author_email = "package-management@trek10.com"
description = "Awsume - A cli that makes using AWS IAM credentials easy"
license = "MIT"
homepage = "https://github.com/trek10inc/awsume"

message = "Thank you for using AWSume! Check us out at https://trek10.com"
