name: Run tests

on:
  push:
    branches:
      - 'releases/**'
      - main
  pull_request:
    branches:
      - 'releases/**'
      - main'

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2018.11.26
      - name: Test
        run: |
          echo "Installing pipenv dependencies"
          PIPENV_NOSPIN=true pipenv install --dev
          pipenv run test
